version: "3.5"
services:
 # Dinopark API container
 dinopark_status_api:
   container_name: 'dinopark_status_api'
   build:
     context: ""
     dockerfile: Dockerfile
   volumes:
     - ./:/project
   ports:
     - 5001:80
   depends_on:
     - mongodb
 # MongoDB container
 mongodb:
   image: mongo:latest
   container_name: "mongodb"
   ports:
     - 27017:27017