swagger: '2.0'
info:
  title: Dinopark Status API
  description: Provides a REST API for Dinopark zone status.
  version: "0.0.1"
schemes:
  - http
basePath: /dinopark_status/v1
produces:
  - application/json
paths:
  /:
    get:
      summary: Health check.
      description: This endpoint returns a welcome message. This can be used to check the health of API.
      tags:
        - Dinopark Status
      responses:
        200:
          description: Successful call.
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'Welcome to the Dinopark Status API!'
        404:
          description: Route not found. Usually indicates an invalid url.
          schema:
            $ref: '#/definitions/ApiError'
  /maintenance_status/:
    get:
      summary: The status of zone based on a unique zone identifier.
      description: This endpoint returns status of a zone.
      parameters:
        - name: zone
          in: query
          type: string
          required: true
          description: "A unique zone identifier."
      tags:
        - Dinopark Status
      responses:
        200:
          description: Successful call.
          schema:
            $ref: '#/definitions/Maintenance_Status'
        400:
          description: Required parameter not in the request.
          schema:
            $ref: '#/definitions/ApiError'
        404:
          description: Route not found. Usually indicates an invalid url. Or the zone provided does not exist in the logs retrieved from NUDLS.
          schema:
            $ref: '#/definitions/ApiError'
        405:
          description: Unsupported operation. Usually indicates that the requested method is not allowed.
          schema:
            $ref: '#/definitions/ApiError'
        503:
          description: Service Unavailable. Usually indicates that an external dependency failed i.e. NUDLS endpoint is unavailable.
          schema:
            $ref: '#/definitions/ApiError'

definitions:
  ApiError:
    type: object
    properties:
      message:
        type: string
  Maintenance_Status:
    type: object
    properties:
      zone:
        type: string
        description: Unique zone identifier.
      maintenance_required:
        type: string
        description: Whether maintenance is required in the zone or not.
